### ISSUE TITLE
Version 1 plan

### ISSUE THREAD

**Issue by davekay100** [graphprotocol/everest-subgraph#1]
## Requirements

See: _Crypto Projects Registry document in notion_

## Proposed User Experience

See: _Crypto Projects Registry document in notion_
 
## Proposed Implementation

More or less this is also explained in See: _Crypto Projects Registry document in notion_

However, I will add: 
- Solium and prettier are used for linting
- The contracts are based of https://github.com/skmgoldin/tcr , but changed heavily due to the requirements. It is mostly simplified
- We are using erc725, as implemented here https://github.com/ERC725Alliance/erc725/tree/master/contracts/contracts
- Truffle, Ethers, and OpenZeppelin contracts and test helpers are used.
- Bonding curve is still being decided upon
- Upgradeability will follow the upgradeability patterns outlined by Open Zeppelin

## Open Questions
- None right now

## Proposed Documentation Updates

* None planned for now. When the app is actually released we might need some documentation.

## Proposed Tests

* Test the bonding curve
* Test the voting
* Test the registry
* Test the parameterization
* We *might* add in static analysis, it depends how long it will take. But it will be valuable for us to learn how to 

## Tasks

- Get the TCR working as required. This involves:
   - TCR voting module working as required
   - TCR registrar working as required
   - TCR Registry working as required
- ERC-725 contracts used as project owners, and are created within the contract, or existing erc725 contracts can be used
- Continuous organization chosen
- Continuous organization implemented
- Bonding curve working as required
- Make all contracts upgradeable
- Write scripts to populate ganache data
- Write the subgraph to track this script data 

### Maybe tasks
- Get the contracts audited professionally
- Implement one of the static analysis libraries

The estimates below are in days.

### Version 1 [~11.5 days, target: Dec 6th (factoring in Dave taking 3 days off)]
_updated target - 12 days from Nov 26th = Dec 16th_
- [x] TCR working
   - [x] Voting - 1 .5 day
   - [x] Registrar - done
   - [x] Registry - done
- [ ] ERC-725 - 1 day (EIP 165 too)
- [ ] Continuous organization chosen and implemented - 2 days
- [ ] Bonding curve - 2 days
- [ ] At this point, get brandon and yaniv to review, while in tandem I work on upgradeability and testing
- [ ] Make all contracts upgradeable - 2 days
- [ ] Full test coverage - 2 days (ADDED IN)
- [ ] Write scripts to populate ganache data - 1.5 days
- [ ] Write subgraph - 1.5 days

Maybe tasks (Total would be 14.5 days)
- [ ] Audit contracts - external task
- [ ] Static analysis - 3 days
- [ ] Implement a solution for `appoveAndCall()` so users don't need to start off doing two txs

### Version 2
- [ ] TBD. I would say that there may not even be a V2. I think we can get there all the way with V1. The only thing would be after implementing it, we notice some things we want to change, and then do so.

**Comment by pcowgill** [comment]
@davekaj Thanks for the update! Happy to help with hacking on this if needed - I'm comfortable with that set of tools.

I'll track progress in this repo so we can get the contracts and subgraph wired up with the front end when they're ready https://github.com/metacartel/everest-web-app

**Comment by davekay100** [comment]
Thanks @pcowgill !

I am still wrapping my head around the project as a whole, and the design is still in flux, so when things are more stable I may reach out for help!
